############################
## General Configurations ##
############################

homeassistant: !include homeassistant.yaml

http: !include http.yaml

logbook:
#discovery:
updater:
conversation:
frontend:
sun:
history:
group: !include group.yaml
input_boolean: !include input_boolean.yaml
automation: !include_dir_list automation
script: !include_dir_list scripts
scene: !include_dir_list scenes

##############
## Software ##
##############

sensor: !include sensors.yaml

device_tracker: !include device_tracker.yaml

ifttt:
  key: !secret ifttt

notify: !include notify.yaml

media_player: !include media_player.yaml

device_sun_light_trigger:
  light_group: group.living_room_lights
  device_group: group.all_mobile_devices
  disable_turn_off: 0

##############
## Hardware ##
##############

light:
- platform: hue
  host: 10.0.1.67
  allow_unreachable: true
- platform: lifx

ecobee:
  api_key: !secret ecobee
  hold_temp: false

zwave:
  usb_path: /dev/ttyACM1
#  config_path: /usr/local/lib/python3.4/dist-packages/libopenzwave-0.3.0b8-py3.4-linux-x86_64.egg/config
  polling_interval: 30000