- platform: time_date
  display_options: 
    - 'time'
- platform: cpuspeed
  name: CPU
- platform: command_line
  name: Free Memory
  command: "head -n '3' '/proc/meminfo' | tail -n 1 | awk 'NR==1{print $2}'"
  unit_of_measurement: "MB"
  value_template: '{{ value | multiply(0.0009765625) | round(0) }}'
- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | multiply(0.001) | round(0) }}'

- platform: wunderground
  api_key: !secret wunderground
  monitored_conditions:
    - weather
    - temp_f
    - feelslike_f
    - feelslike_string
    - heat_index_f
    - heat_index_string
    - dewpoint_f
    - dewpoint_string
    - wind_mph
    - UV
    - pressure_mb
    - wind_dir
    - wind_string
    - relative_humidity
    - visibility_mi
    - precip_today_in
    - precip_today_string
    - solarradiation
    - alerts
- platform: darksky
  api_key: !secret darksky
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - nearest_storm_bearing
    - precip_type
    - precip_intensity
    - precip_probability
    - temperature
    - apparent_temperature
    - dew_point
    - wind_speed
    - wind_bearing
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - ozone
    - minutely_summary
    - hourly_summary
    - daily_summary
    - temperature_max
    - temperature_min
    - apparent_temperature_max
    - apparent_temperature_min
    - precip_intensity_max
- platform: openweathermap
  api_key: !secret openweathermap
  monitored_conditions:
    - weather
    - temperature
    - wind_speed
    - humidity
    - pressure
    - clouds
    - rain
    - snow  
- platform: yweather
  monitored_conditions: 
    - weather
    - weather_current
    - temp_min
    - temp_max
    - wind_speed
    - pressure
    - visibility
    - humidity
    - temperature