alias: 'Turn on all lights when sun sets'
trigger:
  platform: sun
  event: sunset
  offset: "-01:00:00"
condition:
  condition: state
  entity_id: group.all_mobile_devices
  state: 'home'
action:
  service: scene.turn_on
  entity_id: scene.concentrate