alias: 'Turn on all lights @ 7AM'
trigger:
  platform: time
  after: "08:00:00"
condition:
  condition: state
  entity_id: group.all_mobile_devices
  state: 'home'
action:
  service: scene.turn_on
  entity_id: scene.relax