alias: 'Turn off vacation mode when someone comes home'
trigger:
	platform: state
  entity_id: group.all_mobile_devices
  to: 'home'
condition:
  condition: state
  entity_id: input_boolean.vacation
  state: 'on'
action:
  service: input_boolean.turn_off
  entity_id: input_boolean.vacation